version: '3.8'

services: 
  node_backend:
    container_name: node
    image: node:8
    build: 
      context: .
    environment: 
      - EXTERNAL_PORT=3001
      - PGDATABASE=notetaking_db
      - PGUSER=kadir
      - PGPASSWORD=12345
      - PGHOST=node_db
    ports:
      - "3001:3001"      
    depends_on: 
      - node_db
  node_db: 
    container_name: node_db
    image: "postgres:12"
    environment: 
      - POSTGRES_USER=kadir
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=notetaking_db
    ports:
      - "5432:5432"
    volumes:
      - nps_data:/var/lib/postgresql/data

volumes:
  nps_data: {}

  
    